### ISSUE TITLE
Allow base64 or file

### ISSUE THREAD

**Issue by kjcsb1** [siftrics/hydra-python#1]
Currently the API supports a request body of base64 but the Python client doesn't support that. Could the library be enhanced to support base64?

**Comment by siftrics** [comment]
@kjcsb1 Certainly! I will ping you when this feature is added. I estimate a turnaround time within 24 hours.

**Comment by siftrics** [comment]
@kjcsb1 The latest commit [040827579b](https://github.com/siftrics/hydra-python/commit/040827579b8b634d5dff3d810e040ac6539c94f0) resolves this issue.

Documentation here: [https://github.com/siftrics/hydra-python#using-base64-strings-instead-of-file-paths](https://github.com/siftrics/hydra-python#using-base64-strings-instead-of-file-paths)
